/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PriceBookRouteImport } from './routes/price-book'
import { Route as MaterialsRouteImport } from './routes/materials'
import { Route as EstimatesRouteImport } from './routes/estimates'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsStatusRouteImport } from './routes/projects.$status'
import { Route as ProjectsDetailIdRouteImport } from './routes/projects.detail.$id'
import { Route as ProjectsDetailIdAddonRouteImport } from './routes/projects.detail.$id.addon'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PriceBookRoute = PriceBookRouteImport.update({
  id: '/price-book',
  path: '/price-book',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialsRoute = MaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => rootRouteImport,
} as any)
const EstimatesRoute = EstimatesRouteImport.update({
  id: '/estimates',
  path: '/estimates',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsStatusRoute = ProjectsStatusRouteImport.update({
  id: '/projects/$status',
  path: '/projects/$status',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsDetailIdRoute = ProjectsDetailIdRouteImport.update({
  id: '/projects/detail/$id',
  path: '/projects/detail/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsDetailIdAddonRoute = ProjectsDetailIdAddonRouteImport.update({
  id: '/addon',
  path: '/addon',
  getParentRoute: () => ProjectsDetailIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/estimates': typeof EstimatesRoute
  '/materials': typeof MaterialsRoute
  '/price-book': typeof PriceBookRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/projects/$status': typeof ProjectsStatusRoute
  '/projects/detail/$id': typeof ProjectsDetailIdRouteWithChildren
  '/projects/detail/$id/addon': typeof ProjectsDetailIdAddonRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/estimates': typeof EstimatesRoute
  '/materials': typeof MaterialsRoute
  '/price-book': typeof PriceBookRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/projects/$status': typeof ProjectsStatusRoute
  '/projects/detail/$id': typeof ProjectsDetailIdRouteWithChildren
  '/projects/detail/$id/addon': typeof ProjectsDetailIdAddonRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/estimates': typeof EstimatesRoute
  '/materials': typeof MaterialsRoute
  '/price-book': typeof PriceBookRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/projects/$status': typeof ProjectsStatusRoute
  '/projects/detail/$id': typeof ProjectsDetailIdRouteWithChildren
  '/projects/detail/$id/addon': typeof ProjectsDetailIdAddonRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/customers'
    | '/dashboard'
    | '/estimates'
    | '/materials'
    | '/price-book'
    | '/reports'
    | '/settings'
    | '/projects/$status'
    | '/projects/detail/$id'
    | '/projects/detail/$id/addon'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/customers'
    | '/dashboard'
    | '/estimates'
    | '/materials'
    | '/price-book'
    | '/reports'
    | '/settings'
    | '/projects/$status'
    | '/projects/detail/$id'
    | '/projects/detail/$id/addon'
  id:
    | '__root__'
    | '/'
    | '/customers'
    | '/dashboard'
    | '/estimates'
    | '/materials'
    | '/price-book'
    | '/reports'
    | '/settings'
    | '/projects/$status'
    | '/projects/detail/$id'
    | '/projects/detail/$id/addon'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CustomersRoute: typeof CustomersRoute
  DashboardRoute: typeof DashboardRoute
  EstimatesRoute: typeof EstimatesRoute
  MaterialsRoute: typeof MaterialsRoute
  PriceBookRoute: typeof PriceBookRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  ProjectsStatusRoute: typeof ProjectsStatusRoute
  ProjectsDetailIdRoute: typeof ProjectsDetailIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/price-book': {
      id: '/price-book'
      path: '/price-book'
      fullPath: '/price-book'
      preLoaderRoute: typeof PriceBookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materials': {
      id: '/materials'
      path: '/materials'
      fullPath: '/materials'
      preLoaderRoute: typeof MaterialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estimates': {
      id: '/estimates'
      path: '/estimates'
      fullPath: '/estimates'
      preLoaderRoute: typeof EstimatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$status': {
      id: '/projects/$status'
      path: '/projects/$status'
      fullPath: '/projects/$status'
      preLoaderRoute: typeof ProjectsStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/detail/$id': {
      id: '/projects/detail/$id'
      path: '/projects/detail/$id'
      fullPath: '/projects/detail/$id'
      preLoaderRoute: typeof ProjectsDetailIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/detail/$id/addon': {
      id: '/projects/detail/$id/addon'
      path: '/addon'
      fullPath: '/projects/detail/$id/addon'
      preLoaderRoute: typeof ProjectsDetailIdAddonRouteImport
      parentRoute: typeof ProjectsDetailIdRoute
    }
  }
}

interface ProjectsDetailIdRouteChildren {
  ProjectsDetailIdAddonRoute: typeof ProjectsDetailIdAddonRoute
}

const ProjectsDetailIdRouteChildren: ProjectsDetailIdRouteChildren = {
  ProjectsDetailIdAddonRoute: ProjectsDetailIdAddonRoute,
}

const ProjectsDetailIdRouteWithChildren =
  ProjectsDetailIdRoute._addFileChildren(ProjectsDetailIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CustomersRoute: CustomersRoute,
  DashboardRoute: DashboardRoute,
  EstimatesRoute: EstimatesRoute,
  MaterialsRoute: MaterialsRoute,
  PriceBookRoute: PriceBookRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  ProjectsStatusRoute: ProjectsStatusRoute,
  ProjectsDetailIdRoute: ProjectsDetailIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
