/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedPriceBookRouteImport } from './routes/_authenticated/price-book'
import { Route as AuthenticatedMaterialsRouteImport } from './routes/_authenticated/materials'
import { Route as AuthenticatedEstimatesRouteImport } from './routes/_authenticated/estimates'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCustomersRouteImport } from './routes/_authenticated/customers'
import { Route as AuthenticatedProjectsStatusRouteImport } from './routes/_authenticated/projects.$status'
import { Route as AuthenticatedProjectsDetailIdRouteImport } from './routes/_authenticated/projects.detail.$id'
import { Route as AuthenticatedProjectsDetailIdAddonRouteImport } from './routes/_authenticated/projects.detail.$id.addon'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/_authenticated/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/_authenticated/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPriceBookRoute = AuthenticatedPriceBookRouteImport.update({
  id: '/_authenticated/price-book',
  path: '/price-book',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMaterialsRoute = AuthenticatedMaterialsRouteImport.update({
  id: '/_authenticated/materials',
  path: '/materials',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedEstimatesRoute = AuthenticatedEstimatesRouteImport.update({
  id: '/_authenticated/estimates',
  path: '/estimates',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/_authenticated/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCustomersRoute = AuthenticatedCustomersRouteImport.update({
  id: '/_authenticated/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProjectsStatusRoute =
  AuthenticatedProjectsStatusRouteImport.update({
    id: '/_authenticated/projects/$status',
    path: '/projects/$status',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedProjectsDetailIdRoute =
  AuthenticatedProjectsDetailIdRouteImport.update({
    id: '/_authenticated/projects/detail/$id',
    path: '/projects/detail/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedProjectsDetailIdAddonRoute =
  AuthenticatedProjectsDetailIdAddonRouteImport.update({
    id: '/addon',
    path: '/addon',
    getParentRoute: () => AuthenticatedProjectsDetailIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/estimates': typeof AuthenticatedEstimatesRoute
  '/materials': typeof AuthenticatedMaterialsRoute
  '/price-book': typeof AuthenticatedPriceBookRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/projects/$status': typeof AuthenticatedProjectsStatusRoute
  '/projects/detail/$id': typeof AuthenticatedProjectsDetailIdRouteWithChildren
  '/projects/detail/$id/addon': typeof AuthenticatedProjectsDetailIdAddonRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/estimates': typeof AuthenticatedEstimatesRoute
  '/materials': typeof AuthenticatedMaterialsRoute
  '/price-book': typeof AuthenticatedPriceBookRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/projects/$status': typeof AuthenticatedProjectsStatusRoute
  '/projects/detail/$id': typeof AuthenticatedProjectsDetailIdRouteWithChildren
  '/projects/detail/$id/addon': typeof AuthenticatedProjectsDetailIdAddonRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated/customers': typeof AuthenticatedCustomersRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/estimates': typeof AuthenticatedEstimatesRoute
  '/_authenticated/materials': typeof AuthenticatedMaterialsRoute
  '/_authenticated/price-book': typeof AuthenticatedPriceBookRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/projects/$status': typeof AuthenticatedProjectsStatusRoute
  '/_authenticated/projects/detail/$id': typeof AuthenticatedProjectsDetailIdRouteWithChildren
  '/_authenticated/projects/detail/$id/addon': typeof AuthenticatedProjectsDetailIdAddonRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/customers'
    | '/dashboard'
    | '/estimates'
    | '/materials'
    | '/price-book'
    | '/reports'
    | '/settings'
    | '/projects/$status'
    | '/projects/detail/$id'
    | '/projects/detail/$id/addon'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/customers'
    | '/dashboard'
    | '/estimates'
    | '/materials'
    | '/price-book'
    | '/reports'
    | '/settings'
    | '/projects/$status'
    | '/projects/detail/$id'
    | '/projects/detail/$id/addon'
  id:
    | '__root__'
    | '/'
    | '/_authenticated/customers'
    | '/_authenticated/dashboard'
    | '/_authenticated/estimates'
    | '/_authenticated/materials'
    | '/_authenticated/price-book'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/_authenticated/projects/$status'
    | '/_authenticated/projects/detail/$id'
    | '/_authenticated/projects/detail/$id/addon'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedCustomersRoute: typeof AuthenticatedCustomersRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEstimatesRoute: typeof AuthenticatedEstimatesRoute
  AuthenticatedMaterialsRoute: typeof AuthenticatedMaterialsRoute
  AuthenticatedPriceBookRoute: typeof AuthenticatedPriceBookRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedProjectsStatusRoute: typeof AuthenticatedProjectsStatusRoute
  AuthenticatedProjectsDetailIdRoute: typeof AuthenticatedProjectsDetailIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/price-book': {
      id: '/_authenticated/price-book'
      path: '/price-book'
      fullPath: '/price-book'
      preLoaderRoute: typeof AuthenticatedPriceBookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/materials': {
      id: '/_authenticated/materials'
      path: '/materials'
      fullPath: '/materials'
      preLoaderRoute: typeof AuthenticatedMaterialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/estimates': {
      id: '/_authenticated/estimates'
      path: '/estimates'
      fullPath: '/estimates'
      preLoaderRoute: typeof AuthenticatedEstimatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/customers': {
      id: '/_authenticated/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/projects/$status': {
      id: '/_authenticated/projects/$status'
      path: '/projects/$status'
      fullPath: '/projects/$status'
      preLoaderRoute: typeof AuthenticatedProjectsStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/projects/detail/$id': {
      id: '/_authenticated/projects/detail/$id'
      path: '/projects/detail/$id'
      fullPath: '/projects/detail/$id'
      preLoaderRoute: typeof AuthenticatedProjectsDetailIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/projects/detail/$id/addon': {
      id: '/_authenticated/projects/detail/$id/addon'
      path: '/addon'
      fullPath: '/projects/detail/$id/addon'
      preLoaderRoute: typeof AuthenticatedProjectsDetailIdAddonRouteImport
      parentRoute: typeof AuthenticatedProjectsDetailIdRoute
    }
  }
}

interface AuthenticatedProjectsDetailIdRouteChildren {
  AuthenticatedProjectsDetailIdAddonRoute: typeof AuthenticatedProjectsDetailIdAddonRoute
}

const AuthenticatedProjectsDetailIdRouteChildren: AuthenticatedProjectsDetailIdRouteChildren =
  {
    AuthenticatedProjectsDetailIdAddonRoute:
      AuthenticatedProjectsDetailIdAddonRoute,
  }

const AuthenticatedProjectsDetailIdRouteWithChildren =
  AuthenticatedProjectsDetailIdRoute._addFileChildren(
    AuthenticatedProjectsDetailIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedCustomersRoute: AuthenticatedCustomersRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEstimatesRoute: AuthenticatedEstimatesRoute,
  AuthenticatedMaterialsRoute: AuthenticatedMaterialsRoute,
  AuthenticatedPriceBookRoute: AuthenticatedPriceBookRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedProjectsStatusRoute: AuthenticatedProjectsStatusRoute,
  AuthenticatedProjectsDetailIdRoute:
    AuthenticatedProjectsDetailIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
